# Generated by Django 4.2.7 on 2023-11-09 16:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Livro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título do Livro')),
                ('genero', models.CharField(max_length=20, verbose_name='Gênero textual')),
                ('autor', models.CharField(max_length=200, verbose_name='Autor(res)')),
                ('editora', models.CharField(max_length=150, verbose_name='Editora')),
                ('anoPublicacao', models.DateTimeField(verbose_name='Data de publicação')),
                ('unidades', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='LivrosAlugados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataDevolucao', models.DateTimeField()),
                ('dataEmprestado', models.DateTimeField()),
                ('nota', models.CharField(max_length=200, verbose_name='Observação')),
                ('livro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SGCLAapp.livro')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pNome', models.CharField(max_length=200, verbose_name='Primeiro nome')),
                ('uNome', models.CharField(max_length=200, verbose_name='Sobrenome')),
                ('dataNasc', models.DateField(verbose_name='Data de Nascimento')),
                ('livros', models.ManyToManyField(through='SGCLAapp.LivrosAlugados', to='SGCLAapp.livro')),
            ],
        ),
        migrations.AddField(
            model_name='livrosalugados',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SGCLAapp.usuario'),
        ),
    ]
