# Generated by Django 4.2.7 on 2023-11-09 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SGCLAapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livrosalugados',
            name='nota',
            field=models.CharField(default='', max_length=200, verbose_name='Observação'),
        ),
    ]
